const USER_DETAILS="USER_DETAILS";
const PLACE_DETAILS="PLACE_DETAILS";
const LOCATION_DATA_LOGGER="LOCATION_DATA_LOGGER";
module.exports.PLACE_DETAILS=PLACE_DETAILS;
module.exports.USER_DETAILS=USER_DETAILS;
module.exports.LOCATION_DATA_LOGGER=LOCATION_DATA_LOGGER;